
import React, { useContext } from 'react';
import { Inter } from '@next/font/google'
import Head from "next/head";
import HomePage from "../components/HomePage";
import Layout from "../components/Layout";

import { ToDoListProvider } from "../provider/ToDoListProvider";
const inter = Inter({ subsets: ['latin'] })
export default function Home() {

  //const { isConnected, isLoading, isError, address, chainId}=useMetamask();

  return (
    <>
      <Head>
        <title>To Do Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Layout>
        <HomePage>
          
        </HomePage>
        </Layout>
      </main>
    </>
  );
}
