import React, { useContext } from 'react';

import Head from "next/head";

import Layout from "../components/Layout";
import HomePage from "../components/HomePage";

import { ToDoListProvider } from "../provider/ToDoListProvider";
export default function Home() {

  //const { isConnected, isLoading, isError, address, chainId}=useMetamask();

  return (
    <>
      <Head>
        <title>NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Layout>
          <HomePage>
          </HomePage>
        </Layout>
      </main>
    </>
  );
}
